spring.application.name=API-GATEWAY

server.port=8000

# ===============================
# Eureka
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

# ===============================
# User Service Route
# ===============================

spring.cloud.gateway.routes[0].id=USER-SERVICE

spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE

spring.cloud.gateway.routes[0].predicates[0]=Path=/ms1/**

# ===============================
# Vehicle Service Route
# ===============================

spring.cloud.gateway.routes[1].id=VEHICLE-SERVICE

spring.cloud.gateway.routes[1].uri=lb://VEHICLE-SERVICE

spring.cloud.gateway.routes[1].predicates[0]=Path=/ms2/**

# ===============================
# Booking Service Route
# ===============================

spring.cloud.gateway.routes[2].id=BOOKING-SERVICE

spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE

spring.cloud.gateway.routes[2].predicates[0]=Path=/ms3/**

# ===============================
# CORS
# ===============================

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*