spring.application.name=USER-SERVICE
server.port=8001

# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/driveease_db
spring.datasource.username=postgres
spring.datasource.password=Govardhan@2009

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Eureka
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

# ===============================
# Application
# ===============================

server.error.include-message=always
